allocatedMemoryDynamically: false
uploadStorage: local
thumbnailService: \EnjoysCMS\Module\SimpleGallery\Admin\Thumbnail
storageList:
  local:
    \EnjoysCMS\Core\StorageUpload\Local:
      rootDirectory: /public/upload/gallery
      publicUrl: /upload/gallery
      permissionMap:
        dir:
          private: 0755

uploadRules:
  maxSize: 3145728
  allowedExtensions:
    - jpg
    - png
    - jpeg
